### ISSUE TITLE
New metanorma gem

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-utils#1]
This is a utility gem, loaded by metanorma-standoc

**Comment by CAMOBAP** [comment]
@ronaldtse, could you please give me write permission

@ronaldtse, @opoudjis should I propose to move https://github.com/metanorma/metanorma-cli/blob/master/lib/metanorma/cli/stringify_all_keys.rb to metanorma-utils gem, how do you think?

**Comment by ronaldtse** [comment]
You have access now. Sure we can.
