### ISSUE TITLE
mimemagic breaking most builds

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma-utils#10]
https://github.com/metanorma/isodoc/runs/2217999098?check_suite_focus=true

See Dependencies section of https://github.com/mimemagicrb/mimemagic: gem users are now being required to install the Freedesktop.org shared-mime-info database, which presumably also means the build scripts for metanorma all need to be updated.

This has just hit me on release. I'd be happy to use a dumber gem, because we're only detecting common image types. Suggestions welcome.

**Comment by CAMOBAP** [comment]
@opoudjis thanks, I already aware of this, working on the installation of Freedesktop.org.xml in snap, homebrew and chocolatey

**Comment by opoudjis** [comment]
I've switched to marcel, which addresses the issue.
